project:
  type: website

website:
  title: "NGS_Pipelines"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Softwares
        menu: 
          - text: nMyo
            href: http://13.212.140.246:3838/nmyo/
          - text: shinyABC
            href: http://13.212.140.246:3838/shinyABC/
          - text: Foo Lab Data Catalog
            href: http://13.214.207.18:3000/login
          - text: sgRNAapp Primer Design
            href: https://micklee.shinyapps.io/sgrnaapp/
          - text: Foo Lab Cell Line Explorer
            href: https://micklee.shinyapps.io/celllines/
            
            
      - text: In-house Data
        menu: 
          - text: In-house Cardiac Cell-Type Epigenetic Tracks (WashU Browser)
            href: https://tinyurl.com/foo2025
          - text: In-house H3K27ac Human Left Ventricle(UCSC)
            href: https://genome.ucsc.edu/s/cjmlee/hg19_H3K27Ac_LV
            
    right:
      - text: Pipelines
        menu: 
          - text: RNAseq
            href: rnaseq.html
          - text: Running differential analysis for Non-RNAseq data using LIMMA package
            href: limma.html
          - text: CHIPseq
          - text: Hi-C

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

